// <auto-generated />
namespace programowanie_wsi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class googlemaps1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(googlemaps1));
        
        string IMigrationMetadata.Id
        {
            get { return "201803081117211_googlemaps1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
